# Generated by Django 5.1.2 on 2024-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSubnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(max_length=255)),
                ('subnets', models.CharField(max_length=255)),
                ('vlan_name', models.CharField(max_length=255)),
                ('vlan_id', models.IntegerField()),
                ('guest_vrf_local', models.CharField(blank=True, max_length=255, null=True)),
                ('switch_port_pri', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_vrf_sc', models.CharField(blank=True, max_length=255, null=True)),
                ('switch_port_sec', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '002_CoreSubnets',
                'verbose_name_plural': '002_CoreSubnets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.IntegerField()),
                ('i_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subnet', models.CharField(blank=True, max_length=255, null=True)),
                ('subnet_mask', models.CharField(blank=True, max_length=255, null=True)),
                ('default_gateway', models.CharField(blank=True, max_length=255, null=True)),
                ('vrrp_ip_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('vrrp_ip_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('vrf', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcp', models.BooleanField(blank=True, choices=[(None, 'None'), (True, 'True'), (False, 'False')], default=None, null=True)),
                ('dhcp_server_1', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcp_server_2', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '001_VLAN',
                'verbose_name_plural': '001_VLANs',
                'ordering': ['id'],
            },
        ),
    ]
